#!/usr/bin/bash
source $VanRoot/color

vexec() {
    if [ x"$1" == x"ls" ]; then
        while read line; do
            tuple=($line)
            id=${tuple[0]}
            dir=$(echo ${tuple[1]} | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g")
            type=""
            ls_result=$(ls $dir)
            OUTCAR_exist=$(find $dir -name "OUTCAR" -maxdepth 1 | wc -l)
            POSCAR_exist=$(find $dir -name "POSCAR" -maxdepth 1 | wc -l)
            if [ $OUTCAR_exist -gt 0 ]; then
                outcar=$dir/OUTCAR
                type="${RED}VASPJob  $RESET"
                finish=$(grep reached $outcar | wc -l)
                if [ $finish -gt 0 ]; then
                    finish="${Blue}Done$RESET"
                else
                    finish="${RED}Fail$RESET"
                fi
                pot=$(grep TITEL $outcar | awk -F= '{print $2}' | awk '{print $1":"$2}' | xargs | sed "s/ /, /g")
                encut=$(grep ENCUT $outcar | awk '{print $1" "$2" "$3" "$4}')
                last_energy=$(grep "energy without" $outcar | tail -1 | awk '{printf "%10.2f eV", $5}')
                last_energy=${Blue}$last_energy${RESET}
                last_force=$(grep "FORCES:" $outcar | tail -1 | awk '{printf "%6.2f", $5}')
                last_force=${Blue}$last_force${RESET}
                echo -e "${id:0:6}  $type $finish $last_energy $last_force $dir"
                if [ $POSCAR_exist -gt 0 ]; then
                    poscar=$dir/POSCAR
                    atom_symbol=($(sed -n "6p" $poscar))
                    atom_count=($(sed -n "7p" $poscar))
                    atom_pot=($(echo $pot | xargs -d, -n1))
                    echo -e "${id:0:6}  ${GREEN}$pot${RESET}"
                else
                    echo -e "${id:0:6}  ${GREEN}$pot${RESET}"
                fi
                echo -e "${id:0:6}  ${GREEN}$encut${RESET}\n"
            else
                type="${Blue}Directory${RESET}"
                echo -e "${id:0:6}  $type  $dir"
            fi

        done <temp_index
    fi
}
