#!/usr/bin/bash

RED="\033[1;31m"
GREEN="\033[1;32m"
WHITE="\033[1;37m"
BOLD="\033[1m"
RESET="\033[0m"

init(){
  local VanRoot=.van

  if [ ! -d $VanRoot ];then
    echo -e "$BOLD $WHITE Init the Vanager~ $RESET"
    mkdir $VanRoot

	# build-up INDEX
    for directory in `find $WorkDir -type d`
    do
      base_directory=`basename $directory`
      if [ x"$base_directory" != x".van" ];then
        md5=`echo "$directory" | md5sum | awk '{print $1}'`
        echo -e "$md5 \t $directory" >> $VanRoot/INDEX
      fi
    done
	
	# build-up TAGS
    for file in `awk '{print $2}' $VanRoot/INDEX`
	do 
	  while [[ "$file" != "$WorkDir" ]]
	  do 
		tag=`basename $file`
		echo $tag
		file=${file%/*}
      done >> $VanRoot/temp_tags
    done
	sort $VanRoot/temp_tags | uniq > $VanRoot/TAGS

	# end initialization
	rm -rf $VanRoot/temp_tags
	echo -e "$BOLD $WHITE The Vanager Initialization success~ $RESET"
  else
    echo -e "$RED The Vanager have been initialized before, stop it! $RESET"
  fi
}

tags(){
  local i=0
  for tag in `cat $VanDir/TAGS`
  do 
    ((i++))
    remainder=`echo $i%6 | bc`
    if [ $remainder -eq 0 ];then 
      echo
    else 
      printf "%-30s" $tag
    fi
  done | more
} 

search(){
  local tag=$1
  awk '{if($2 ~ "'$tag'"){print substr($1, 1, 6), "\t", $2}}' $VanDir/INDEX | grep $tag --color
}

vcd(){
  target=`grep "^$1" $VanDir/INDEX | awk '{print $2}'`
  cd $target
}

# locate VanDir
WorkDir=`pwd`
VanDir=$WorkDir
while [[ $VanDir =~ "/" ]]
do
  if [ -d $VanDir/.van ];then
    VanDir=$VanDir/.van
    break
  else
    VanDir=${VanDir%/*}
  fi
done

# Parse Arguments
if [ x"$1" == x"init" ];then
  init
else
  if [ x"$VanDir" == x"" ];then
    echo -e "$RED No Vanager Project exist, stop! $RESET"
  else
    if [ x"$1" == x"tags" ];then
  	  tags
    elif [ x"$1" == x"search" ];then
      search $2
    elif [ x"$1" == x"cd" ];then
      vcd $2
    elif [ x"$1" == x"" ];then
      cd $VanDir && cd ..
    fi
  fi
fi
